import os
import time
import hashlib
import logging
import base64
from pathlib import Path
from google import genai
from google.genai import types

logger = logging.getLogger(__name__)


def generate_image(
    prompt: str,
    input_image: str = None,
    output_dir: str = "generated_images",
    model: str = "gemini-2.0-flash-exp-image-generation"
) -> str:
    """
    Google GenAI SDK (Gemini/Nano Banana) を使用して画像を生成・編集し、ローカルに保存する。

    Args:
        prompt: 画像生成・編集のためのプロンプト
        input_image: 入力画像のパス（編集する場合に指定）
        output_dir: 画像の保存先ディレクトリ
        model: 使用するモデル (default: gemini-2.0-flash-exp-image-generation)
               - gemini-2.0-flash-exp-image-generation (Gemini 2.0 Flash)
               - gemini-2.5-flash-preview-04-17 (Nano Banana)

    Returns:
        保存された画像のパス

    Examples:
        # テキストから画像生成
        generate_image("A cute cat sitting on a sofa")
        
        # 画像編集（スタイル変換）
        generate_image("この画像を油絵風に変換してください", input_image="photo.jpg")
        
        # 画像編集（要素追加）
        generate_image("背景に花火を追加してください", input_image="night_sky.png")
        
        # 画像編集（要素削除・変更）
        generate_image("人物の服を赤いドレスに変更してください", input_image="portrait.jpg")
    """
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY") or os.environ.get("GENAI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY, GOOGLE_API_KEY, or GENAI_API_KEY environment variable is not set.")
    api_key = api_key.strip().strip('"').strip("'")

    client = genai.Client(api_key=api_key)

    try:
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)

        # コンテンツを構築
        contents = []
        
        # 入力画像がある場合は追加
        if input_image:
            image_path = Path(input_image)
            if not image_path.exists():
                raise FileNotFoundError(f"Input image not found: {input_image}")
            
            # 画像の MIME タイプを判定
            suffix = image_path.suffix.lower()
            mime_types = {
                '.jpg': 'image/jpeg',
                '.jpeg': 'image/jpeg',
                '.png': 'image/png',
                '.gif': 'image/gif',
                '.webp': 'image/webp',
            }
            mime_type = mime_types.get(suffix, 'image/png')
            
            # 画像を読み込んで base64 エンコード
            with open(image_path, 'rb') as f:
                image_bytes = f.read()
            
            # 画像パートを追加
            contents.append(types.Part.from_bytes(data=image_bytes, mime_type=mime_type))
            logger.info(f"Input image loaded: {input_image} ({mime_type})")
        
        # テキストプロンプトを追加
        contents.append(prompt)

        # Gemini 2.0 Flash / Nano Banana で画像生成
        response = client.models.generate_content(
            model=model,
            contents=contents,
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE", "TEXT"],
            )
        )

        # レスポンスから画像を取得
        image_data = None
        text_response = None
        for part in response.candidates[0].content.parts:
            if hasattr(part, 'inline_data') and part.inline_data:
                image_data = part.inline_data.data
            elif hasattr(part, 'text') and part.text:
                text_response = part.text
        
        if not image_data:
            error_msg = f"No image was generated by the model."
            if text_response:
                error_msg += f" Model response: {text_response}"
            raise RuntimeError(error_msg)

        timestamp = time.time_ns()
        prompt_hash = hashlib.md5(prompt.encode()).hexdigest()[:8]
        filename = f"gen_{timestamp}_{prompt_hash}.png"
        file_path = output_path / filename

        with open(file_path, "wb") as f:
            f.write(image_data)

        logger.info(f"Image generated and saved to {file_path}")
        
        result = str(file_path)
        if text_response:
            result += f"\n\nModel comment: {text_response}"
        
        return result

    except Exception as e:
        logger.error(f"Error generating image: {e}")
        raise
